### ISSUE TITLE
Acclimate with Files

### ISSUE THREAD

**Issue by smarple222** [smarple222/example#1]
## Tasks
- [x] Review file.xlsx ⭐ 
- [ ] Reverse engineer file.xlsx
    - [x] break down logic in excel
    - [ ] gather data inputs
    - [ ] write code to automate
    - [ ] Compare and contrast results
    - [ ] verify with client
    - [ ] get ready to deploy in production

---
### Questions
* Who are my POCs? 
   `answer: John Smith, The little mermaid, and Jerry Mcguire`
* Do I need access to various systems?

--- 
### Email from Elvis Presley
   ```
   I can't find my blue suede shoes!
   I'm all shook up, today...

   Sincerely,

   Elvis
   ```
❓ ❓ ❓ 
<br> **I'm not sure what his meaning is here.**
**Does this mean he's on his way??**

---

## Here is what I know about the files:

File | location | Notes
-|-|-
file1 | O drive | made up of a bunch of pivot tables, summing by year
file2 | D drive | documentation on how everything works
file3 | M drive | raw data results from a query taken from system A.  Query needs improvement, but may be useful

**Comment by smarple222** [comment]
## Information from Talya:
File | Information
-|-
BB 2022 Q1-2.xlsx | Sent to David late yesterday afternoon.  See Attached Email.
EB 2022 Q3-2.xlsx | Sent to David late yesterday afternoon.  See Attached Email.
YTD 2022 Q3-3.xlsx | Sent to David late yesterday afternoon.  See Attached Email.
DDRS 4510 Q3 2022 (Combined).xlsx | Sent to David late yesterday afternoon.  See Attached Email. 
DDRS 4610 COMBINED Q3 2022-.xlsx | Sent to David late yesterday afternoon.  See Attached Email. 
SBR DRILL DOWN Q3 2022 repull.xlsx | See Attached SAFE.
OBIEE-DEAMS Feed data source | See Attached SAFE. USACE (CEFMS) and DEAMS Funding Comparison spreadsheets.   It comes from Departmental Reporting and the DEAMS JV backout process they do monthly. 
USACE-OBIEE Feed data source | See Attached SAFE. USACE (CEFMS) and DEAMS Funding Comparison spreadsheets.   It comes from Departmental Reporting and the DEAMS JV backout process they do monthly. 
JVs data source | This is just GAFSR IQ JV queries looking by dollar amount, BS, etc.  .  See Attached SAFE.
In / Out-of-scope table sources | This is determined by the Air Force.  The core inscope appropriations comes from the Air Force Assertion in 2014 before the audit, and the distribution activity stays true to those core appropriations.  I put the snippet of those core inscope appropriations from the Assertion into the SOPs in the glossary.  There will be a few new appropriations each year (recently mainly spaceforce appropriations) that are discovered during the recon process when balancing.  So your source, would be the snippet I of the inscope appropriations in the SOPs in the glossary.  And includes anything NOT expired.

**Comment by smarple222** [comment]
## Tasks
- [x] Review Q3 2022 FD2M Recon V3.xlsx (Distributions)
- [x] Perform 1st pass on distribution checklist
    - [x]  Create links for where numbers are coming from for major tabs
    - [x] Create template for distribution
- [x] Review Airstaff Recon file
- [x] Review MAJCOM Recon file
- [x] Identify where Airstaff and Majcom recons intersect Distributions
- [ ] Break down logic for:
    - [x] AFM Apportionment Recal
    - [x] Scope Summary
    - [ ] QDD To MAJCOM ⭐ 
    - [x] Distribution to MAJCOM
        - Lookups point to pivot tables
        - pivot tables point to unknown sources
        - ---
        - [x] request the following tables from Talya Spann (received ☑️) : 
            - All have been requested:  9-19-2022
            -  [x] BB 2022 Q1-2.xlsx
            -  [x] EB 2022 Q3-2.xlsx
            -  [x] YTD 2022 Q3-3.xlsx
            -  [x] DDRS 4510 Q3 2022 (Combined).xlsx
            -  [x] DDRS 4610 COMBINED Q3 2022-.xlsx
            - [x] SBR DRILL DOWN Q3 2022 repull.xlsx
            -  [x] OBIEE-DEAMS Source
            -  [x] USACE-OBIEE Feed Source
            -  [x] JVs Source
            - [x] In / Out of scope table sources ( Funds Dist to Majcom SOP )
---
### Note
⭐  Any combined tables identified that are not queried as such, can either be:
   - changed via the query coming out OR
   - can be combined in a class method and extracted after<br></br>
- [x] Analyze and Identify Integration Points for the following:
    - [x] BB 2022 Q1-2.xlsx
       - `Sum of compute_0007 in tab, BB PIVOT`
    - [x] EB 2022 Q3-2.xlsx
       - `Sum of compute_0007 in tab, EB PIVOT`
    - [x] YTD 2022 Q3-3.xlsx
       - `Sum of compute_0007 in tab, YTD PIVOT`
       - `data may not be accurate.  further testing is required`
    - [x] DDRS 4510 Q3 2022 (Combined).xlsx
       - `Sum of AMT in tab, DDRS 4510 PIVOT`
    - [x] DDRS 4610 COMBINED Q3 2022-.xlsx
       - `Sum of AMT in tab, DDRS 4610 PIVOT`
    - [x] SBR DRILL DOWN Q3 2022 repull.xlsx 
       - `Sum by trial balance in tab, SBR Q3 2022 Drill Down PIVOT`
    - [x]  OBIEE-DEAMS Source
    - [x] USACE-OBIEE Feed Source
    - [x] JVs Source
    - [x] In / Out of scope table sources ( Funds Dist to Majcom SOP )

**Comment by smarple222** [comment]
## Signatures and Scope Summary
❗ means results don't match
❓ means data missing / question could not be answered
✔️ means check was completed

### Signatures
- [ ] Ensure Signatures exist, with current signing and certificates.  
    - One for the person completing the recon, and 
    - one for the Supervisor or AU Lead that reviews and/or approves it.  
- [x] The workbook refers to the correct Systems and reconciliation period

### Scope Summary
- [x] Check that the total for “A” column on the GL Account equals line/Budgetary Resource 2204 from the current quarter SBR tab.   
    - Balanced numbers include Space Force totals as well. Will be split out in FY 23.
- [ ] Check totals for 4510 and 4610 for Scope Summary against the Distribution to MAJCOM and QDD to MAJCOM tabs
    - [x] ❗ GLAC 4510 + 4610 = Ending Balance GLAC 4510 + Ending Balance GLAC 4610
        - Majcom tab should be **_filtered to current year only_** 
    - [ ] ❓  GLAC 4510 + 4610 = QDD to MAJCOM! QDD YTD 
        - highlighted in blue
        - `No data found on QDD tab`
- [x] out-of-scope totals = the breakdowns at the top of the tab for the following:
    - [x] 4510, 
    - [x] 4590, 
    - [x] 4610, 
    - [x] 4700
- [x] ❗   Compare beginning balance table = SBR BB PRIOR! 2204?   
- [x] ❗ Beginning balance table! In-scope GLAC 4510 = Distribution to MAJCOM! Beginning Balance totals
- [x] ❗ Beginning balance table! In-scope GLAC 4610 = Distribution to MAJCOM! Beginning Balance totals
- [x] Beginning Balance Out-of-scope GLAC 4510 = breakdowns for those GLACs further down the tab
- [x] ❗ Beginning Balance Out-of-scope GLAC 4610 = breakdowns for those GLACs further down the tab

**Comment by smarple222** [comment]
### AFM Apportionment Recall
- [x] ❗ Does column D (AFM PATS 1,10,14 & 16) equal column D from the “Appropriations Realized” tab in the Funds Receipt Reconciliation (be sure to use same quarter)?
- [x] Does column E (PATs 12 and 23) equal column D from the Transfers tab in the Funds Receipt Recon? 
    - Note: transfers from the FR Reconciliation? 
    - Note:  includes out of scope, so make sure the FD number includes that as well.  
    - Should be detailed under column E, with notes
- [x] Does column F (PAT 15) equal column D in the Rescissions tab of the Funds Receipt Reconciliation?

### FD2B Funds Distribution to Base (Scope FD2B Tab)
❗ `I don't see this tab.`  
`This is an external spreadsheet`
- [ ] In the “Scope FD2B” tab:
    - [ ] ensure that 4610 AFM number at the top line, Column 9 = the same number in the FD2M recon, “Distribution to MAJCOM” tab, 4610 number, column 9.   This represents the ending balance for Native GLAC 4610.
- [ ] Comparing AFM amounts available for Distro and AFM amounts distributed to Bases.  In FD2M, “Distro to MAJCOM” tab, column 15, which is total AFM Available for Distro for 4610.  Compare with FD2B, “Scope FD2B” tab, 6a AFM total, amount distributed in current quarter
Any variances should be documented at bottom of this tab describing the differences.
- [ ] To ensure the GAFS-R totals from the MAJCOM file are same, you look at tab “Scope FD2B”, column 12, at the top, called “Recalculated Distribution”.  Top total should equal same amount in FB2M, “Distro to MAJCOM” tab, column 12, Recalculated Distro for Native GLAC 4610.
This establishes that the GAFS totals from FD2M were transferred accurately to FD2B.  
- [ ] Check that AFM to GAFSR Variance in this recon is accurate, by checking tab “Scope FD2B” Column 16, top number for 4610 with FD2M recon, tab “Distribution to MAJCOM” Column 16.  Variance totals should be explained down below

**Comment by smarple222** [comment]
### FD2B QX YYYY Tab
❗ `Am not seeing this tab`
`This is an external spreadsheet`

- [ ] Check Total for Column J, “AVAILABLE_FOR_DIST from prior quarters”.  This total should equal the following.  Using the source file, “QXYYY MAJCOM Recon” (PREVIOUS QUARTER) spreadsheet, look for the totals in the last column “AVAILABLE FOR DIST”.   See NOTE to the right to get correct total.   	
NOTE:  When checking the source file, QXYYY MAJCOM Recon.xls, it must be for PREVIOUS quarter.  Last column, filter out all expired appropriations in column B, and filter out all XXXX year appropriations in column C, finally filter out all Out of Scope items that are left in column A.   The total you get in column P should then match Column J total in the FD2B QX YYYY Tab.
- [ ] Check total for Column O, “AVAILABLE_FOR_DIST”.  This should equal the following.  Using the source file “QXYYY MAJCOM Recon” (Current QUARTER) spreadsheet, look for the totals in column P“AVAILABLE FOR DIST”.   See NOTE to the right to get correct total.
NOTE:  When checking the source file, QXYYY MAJCOM Recon.xls, it must be for CURRENT quarter. Total for Column P, filter out all expired appropriations in column B, and filter out all XXXX year appropriations in column C, finally filter out all Out of Scope items that are left in column A.   The total you get in column P should then match Column O total in the FD2B QX YYYY Tab.    
- [ ] Check for Cumulative Availability, Column Q in the FD2B QX YYYY tab.   To do this, you will need the source file “QXYYY MAJCOM Recon” (Current QUARTER) spreadsheet.  Create an additional Column (Q), called “AVAILABLE FOR DIST MINUS WITHOLDS”.  Subtract totals in Column O from totals in Column P, to get your totals for Column Q.  This total should equal the total in Column P of the FD2B recon.  This total will then be added to the total from F.5 of this checklist.  That total should equal Column Q of the FD2B QX YYYY tab.
Click or tap here to enter text.

### DEAMS Comparison
- [x] DEAMS Comparison added to overall Recon workbook as OBIEE DEAMS FEED tab in the FD2M recon.
    - OBIEE is Oracle Business Intelligence Enterprise Edition.  
- [x] ❗ Distribution to MAJCOM! Net Variance total = OBIEE-DEAMS FEED! total
- [x] Match OBIEE 3830 total with MAJCOM 3830 total in column AA
    - To make sure the breakdowns are as accurate as the grand totals
    - should match all totals between OBIEE and MAJCOM ⭐
